// frontend/src/components/Navbar.vue
<template>
    <div class="sticky z-50 top-0 h-14 border-b flex items-center bg-gray-100 justify-between px-[10px] md:px-[80px]">
        <div class="flex items-center gap-2">
            <div><v-icon name="ai-sci-hub-square" width="32" height="32" /></div>

            <h1 class="text-[20px]">Coursera</h1>
        </div>


        <div class="flex items-center gap-10">
            <div class="user-info items-center flex gap-2">
                <div class="image border-2 rounded-full p-2">
                    <img class="w-[24px] h-[24px]" :src="vue" alt="Profile">
                </div>

                <div class="email flex flex-col gap-[1px]">
                    <h1 class="text-[12px]">student</h1>
                    <h1 class="text-[12px]">lokeshkumar@mail.com</h1>
                </div>
            </div>

            <div class="sign-out">
                <button class="border-2 px-4 py-2 cursor-pointer rounded-full hover:bg-purple-500 hover:text-white">Sign Out</button>
            </div>
        </div>

    </div>
</template>

<script>
import vue from "../assets/vue.svg";

export default {
  data() {
    return {
      vue
    }
  }
}
</script>

// frontend/src/components/Navbar.jsx
import React from "react";
import { GiEgyptianBird } from "react-icons/gi";

const Navbar = () => {
  return (
    <div className="h-16 flex-shrink-0 flex justify-between items-center px-[10px] md:px-[80px] border-b border-gray-400 bg-gray-100 sticky top-0 z-50">
      <div className="flex items-center gap-2">
        <div>
          <GiEgyptianBird className="h-[24px] w-[24px]" />
        </div>
        <span className="font-semibold">Coursera</span>
      </div>

      <div className="flex items-center gap-6">
        <div className="flex items-center gap-4">
          <span className="font-semibold">Student</span>
          <img
            src="https://media.licdn.com/dms/image/C5103AQEv1nBXNAmuOw/profile-displayphoto-shrink_400_400/0/1540870660730?e=1724284800&v=beta&t=t5GRaGMxx_xyhbSTZpaK1xbJFLYLhOVEkzhcumhsELM"
            className="h-[32px] w-[32px] rounded-full"
          />
          <div className="hidden md:flex flex-col">
            <span className="text-[12px]">lokesh</span>
            <span className="text-[12px]">lokesh@mail.com</span>
          </div>
        </div>
        <button className="px-4 py-2 border border-gray-400 rounded-full hover:text-white hover:bg-red-700">
          Sign Out
        </button>
      </div>
    </div>
  );
};

export default Navbar;
